### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by alejandronanez** [alejandronanez/redux-react-boilerplate#1]
- [x] React hot reloading
- [x] Redux basic structure
- [x] Readme
- [x] License
- [x] Contributors
- [x] Website
- [x] Say this is opinionated
- [x] Say thanks to `hjs-webpack` package
